[package]
name = "postgresd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# import postgres dependency, including version
[dependencies]
postgres = "0.19.2"

[lib]
name="hello"